import type { Tree } from "../../types";

export const protection: Tree = {
    specIcon: "spell_holy_devotionaura.png",
    name: "Protection",
    backgroundImage: "src/assets/images/paladin/background-paladin-protection.webp",
    talents: [
        {
            id: "spell_holy_devotionaura",
            ranks: [
                "Increases the armor bonus of your Devotion Aura by 8%.",
                "Increases the armor bonus of your Devotion Aura by 16%.",
                "Increases the armor bonus of your Devotion Aura by 24%.",
                "Increases the armor bonus of your Devotion Aura by 32%.",
                "Increases the armor bonus of your Devotion Aura by 40%."
            ],
            row: 0,
            name: "Improved Devotion Aura",
            col: 1,
            maxPoints: 5,
            icon: "spell_holy_devotionaura.png",
            points: 0
        },
        {
            id: "ability_defend",
            ranks: [
                "Damaging melee and ranged attacks against you have a 10% chance to increase your chance to block by 6%.  Lasts 10 seconds or 5 blocks.",
                "Damaging melee and ranged attacks against you have a 10% chance to increase your chance to block by 12%.  Lasts 10 seconds or 5 blocks.",
                "Damaging melee and ranged attacks against you have a 10% chance to increase your chance to block by 18%.  Lasts 10 seconds or 5 blocks.",
                "Damaging melee and ranged attacks against you have a 10% chance to increase your chance to block by 24%.  Lasts 10 seconds or 5 blocks.",
                "Damaging melee and ranged attacks against you have a 10% chance to increase your chance to block by 30%.  Lasts 10 seconds or 5 blocks."
            ],
            row: 0,
            name: "Redoubt",
            col: 2,
            maxPoints: 5,
            icon: "ability_defend.png",
            points: 0
        },
        {
            id: "ability_rogue_ambush",
            ranks: [
                "Increases your chance to hit with melee weapons and spells by 1%.",
                "Increases your chance to hit with melee weapons and spells by 2%.",
                "Increases your chance to hit with melee weapons and spells by 3%."
            ],
            row: 1,
            name: "Precision",
            col: 0,
            maxPoints: 3,
            icon: "ability_rogue_ambush.png",
            points: 0
        },
        {
            id: "spell_holy_sealofprotection",
            ranks: [
                "Reduces the cooldown of your Hand of Protection by 60 sec and increases the duration of your Hand of Freedom by 2 sec.",
                "Reduces the cooldown of your Hand of Protection by 120 sec and increases the duration of your Hand of Freedom by 4 sec."
            ],
            row: 1,
            name: "Guardian's Favor",
            col: 1,
            maxPoints: 2,
            icon: "spell_holy_sealofprotection.png",
            points: 0
        },
        {
            id: "spell_holy_devotion",
            ranks: [
                "Increases your armor value from items by 2%.",
                "Increases your armor value from items by 4%.",
                "Increases your armor value from items by 6%.",
                "Increases your armor value from items by 8%.",
                "Increases your armor value from items by 10%."
            ],
            row: 1,
            name: "Toughness",
            col: 3,
            maxPoints: 5,
            icon: "spell_holy_devotion.png",
            points: 0
        },
        {
            id: "spell_magic_magearmor",
            ranks: [
                "Places a Blessing on the friendly target, increasing total stats by 10% for 600 seconds.  Players may only have one Blessing on them per Paladin at any one time."
            ],
            row: 2,
            name: "Blessing of Kings",
            col: 0,
            maxPoints: 1,
            icon: "spell_magic_magearmor.png",
            points: 0
        },
        {
            id: "spell_holy_sealoffury",
            ranks: [
                "While Righteous Fury is active, all damage taken is reduced by 2% and increases the amount of threat generated by your Righteous Fury spell by 16%.",
                "While Righteous Fury is active, all damage taken is reduced by 4% and increases the amount of threat generated by your Righteous Fury spell by 33%.",
                "While Righteous Fury is active, all damage taken is reduced by 6% and increases the amount of threat generated by your Righteous Fury spell by 50%."
            ],
            row: 2,
            name: "Improved Righteous Fury",
            col: 1,
            maxPoints: 3,
            icon: "spell_holy_sealoffury.png",
            points: 0
        },
        {
            id: "inv_shield_06",
            ranks: [
                "Increases the amount of damage absorbed by your shield by 10%.",
                "Increases the amount of damage absorbed by your shield by 20%.",
                "Increases the amount of damage absorbed by your shield by 30%."
            ],
            row: 2,
            name: "Shield Specialization",
            col: 2,
            maxPoints: 3,
            requires: {
                id: 0,
                points: 5
            },
            icon: "inv_shield_06.png",
            points: 0
        },
        {
            id: "spell_holy_mindsooth",
            ranks: [
                "Increases the effect of your Concentration Aura by an additional 5% and reduces the duration of any Silence or Interrupt effect used against an affected group member by 10%.  The duration reduction does not stack with any other effects.",
                "Increases the effect of your Concentration Aura by an additional 10% and reduces the duration of any Silence or Interrupt effect used against an affected group member by 20%.  The duration reduction does not stack with any other effects.",
                "Increases the effect of your Concentration Aura by an additional 15% and reduces the duration of any Silence or Interrupt effect used against an affected group member by 30%.  The duration reduction does not stack with any other effects."
            ],
            row: 2,
            name: "Improved Concentration Aura",
            col: 3,
            maxPoints: 3,
            icon: "spell_holy_mindsooth.png",
            points: 0
        },
        {
            id: "spell_holy_stoicism",
            ranks: [
                "Increases your resistance to Stun effects by an additional 5% and reduces the chance your spells will be dispelled by an additional 15%.",
                "Increases your resistance to Stun effects by an additional 10% and reduces the chance your spells will be dispelled by an additional 30%."
            ],
            row: 3,
            name: "Stoicism",
            col: 0,
            maxPoints: 2,
            icon: "spell_holy_stoicism.png",
            points: 0
        },
        {
            id: "spell_holy_sealofmight",
            ranks: [
                "Decreases the cooldown of your Hammer of Justice spell by 5 sec.",
                "Decreases the cooldown of your Hammer of Justice spell by 10 sec.",
                "Decreases the cooldown of your Hammer of Justice spell by 15 sec."
            ],
            row: 3,
            name: "Improved Hammer of Justice",
            col: 1,
            maxPoints: 3,
            icon: "spell_holy_sealofmight.png",
            points: 0
        },
        {
            id: "spell_magic_lesserinvisibilty",
            ranks: [
                "Increases your Defense skill by 4.",
                "Increases your Defense skill by 8.",
                "Increases your Defense skill by 12.",
                "Increases your Defense skill by 16.",
                "Increases your Defense skill by 20."
            ],
            row: 3,
            name: "Anticipation",
            col: 2,
            maxPoints: 5,
            icon: "spell_magic_lesserinvisibilty.png",
            points: 0
        },
        {
            id: "spell_holy_improvedresistanceauras",
            ranks: [
                "All spell damage taken is reduced by 2%.",
                "All spell damage taken is reduced by 4%."
            ],
            row: 4,
            name: "Spell Warding",
            col: 0,
            maxPoints: 2,
            icon: "spell_holy_improvedresistanceauras.png",
            points: 0
        },
        {
            id: "spell_nature_lightningshield",
            ranks: [
                "Places a Blessing on the friendly target, reducing damage dealt from all sources by up to 10 for 600 seconds.  In addition, when the target blocks a melee attack the attacker will take 14 Holy damage.  Players may only have one Blessing on them per Paladin at any one time."
            ],
            row: 4,
            name: "Blessing of Sanctuary",
            col: 1,
            maxPoints: 1,
            icon: "spell_nature_lightningshield.png",
            points: 0
        },
        {
            id: "spell_holy_blessingofstrength",
            ranks: [
                "Gives you a 2% chance after being hit by any damaging attack that the next 4 weapon swings within 8 seconds will generate an additional attack.",
                "Gives you a 4% chance after being hit by any damaging attack that the next 4 weapon swings within 8 seconds will generate an additional attack.",
                "Gives you a 6% chance after being hit by any damaging attack that the next 4 weapon swings within 8 seconds will generate an additional attack.",
                "Gives you a 8% chance after being hit by any damaging attack that the next 4 weapon swings within 8 seconds will generate an additional attack.",
                "Gives you a 10% chance after being hit by any damaging attack that the next 4 weapon swings within 8 seconds will generate an additional attack."
            ],
            row: 4,
            name: "Reckoning",
            col: 2,
            maxPoints: 5,
            icon: "spell_holy_blessingofstrength.png",
            points: 0
        },
        {
            id: "spell_holy_divineintervention",
            ranks: [
                "Increases your total Stamina by 3%, reduces the cooldown of your Divine Shield spell by 30 sec and reduces the attack speed penalty by 50%.",
                "Increases your total Stamina by 6%, reduces the cooldown of your Divine Shield spell by 60 sec and reduces the attack speed penalty by 100%."
            ],
            row: 5,
            name: "Sacred Duty",
            col: 0,
            maxPoints: 2,
            icon: "spell_holy_divineintervention.png",
            points: 0
        },
        {
            id: "inv_sword_20",
            ranks: [
                "Increases all damage you deal when a one-handed melee weapon is equipped by 1%.",
                "Increases all damage you deal when a one-handed melee weapon is equipped by 2%.",
                "Increases all damage you deal when a one-handed melee weapon is equipped by 3%.",
                "Increases all damage you deal when a one-handed melee weapon is equipped by 4%.",
                "Increases all damage you deal when a one-handed melee weapon is equipped by 5%."
            ],
            row: 5,
            name: "One-Handed Weapon Specialization",
            col: 2,
            maxPoints: 5,
            icon: "inv_sword_20.png",
            points: 0
        },
        {
            id: "spell_holy_blessingofprotection",
            ranks: [
                "Increases damage caused by your Holy Shield by 10% and increases the number of charges of your Holy Shield by 2.",
                "Increases damage caused by your Holy Shield by 20% and increases the number of charges of your Holy Shield by 4."
            ],
            row: 6,
            name: "Improved Holy Shield",
            col: 0,
            maxPoints: 2,
            requires: {
                id: "spell_holy_blessingofprotection",
                points: 1
            },
            icon: "spell_holy_blessingofprotection.png",
            points: 0
        },
        {
            id: "spell_holy_blessingofprotection",
            ranks: [
                "Increases chance to block by 30% for 10 seconds and deals 59 Holy damage for each attack blocked while active.  Damage caused by Holy Shield causes 35% additional threat.  Each block expends a charge.  4 charges."
            ],
            row: 6,
            name: "Holy Shield",
            col: 1,
            maxPoints: 1,
            requires: {
                id: "spell_nature_lightningshield",
                points: 1
            },
            icon: "spell_holy_blessingofprotection.png",
            points: 0
        },
        {
            id: "spell_holy_ardentdefender",
            ranks: [
                "When you have less than 35% health or when an attack brings you under 35% health, all damage taken is reduced by 6%.",
                "When you have less than 35% health or when an attack brings you under 35% health, all damage taken is reduced by 12%.",
                "When you have less than 35% health or when an attack brings you under 35% health, all damage taken is reduced by 18%.",
                "When you have less than 35% health or when an attack brings you under 35% health, all damage taken is reduced by 24%.",
                "When you have less than 35% health or when an attack brings you under 35% health, all damage taken is reduced by 30%."
            ],
            row: 6,
            name: "Ardent Defender",
            col: 2,
            maxPoints: 5,
            icon: "spell_holy_ardentdefender.png",
            points: 0
        },
        {
            id: "spell_holy_weaponmastery",
            ranks: [
                "Reduces your chance to be dodged or parried by 0.25% and increases your total Stamina by 2%.",
                "Reduces your chance to be dodged or parried by 0.5% and increases your total Stamina by 4%.",
                "Reduces your chance to be dodged or parried by 0.75% and increases your total Stamina by 6%.",
                "Reduces your chance to be dodged or parried by 1% and increases your total Stamina by 8%.",
                "Reduces your chance to be dodged or parried by 1.25% and increases your total Stamina by 10%."
            ],
            row: 7,
            name: "Combat Expertise",
            col: 2,
            maxPoints: 5,
            icon: "spell_holy_weaponmastery.png",
            points: 0
        },
        {
            id: "spell_holy_avengersshield",
            ranks: [
                "Hurls a holy shield at the enemy, dealing 270 Holy damage, Dazing them and then jumping to additional nearby enemies.  Affects 3 total targets.  Lasts 6 seconds."
            ],
            row: 8,
            name: "Avenger's Shield",
            col: 1,
            maxPoints: 1,
            requires: {
                id: "spell_holy_blessingofprotection",
                points: 1
            },
            icon: "spell_holy_avengersshield.png",
            points: 0
        }
    ]
};