import type { Tree } from './types'

export const initialTalentTrees: Tree[] = [
  {
    name: 'Arms',
    backgroundImage:
      'src/assets/images/warrior/background-warrior-arms.webp',
    talents: [
      {
        id: 'ability_rogue_ambush',
        name: 'Improved Heroic Strike',
        ranks: [
          'Reduces the cost of your Heroic Strike ability by 1 rage point.',
          'Reduces the cost of your Heroic Strike ability by 2 rage points.',
          'Reduces the cost of your Heroic Strike ability by 3 rage points.',
        ],
        row: 0,
        col: 0,
        points: 0,
        maxPoints: 3,
        icon: 'ability_rogue_ambush.png',
      },

      {
        id: 'ability_parry',
        name: 'Deflection',
        ranks: [
          'Increases your Parry chance by 1%.',
          'Increases your Parry chance by 2%.',
          'Increases your Parry chance by 3%.',
          'Increases your Parry chance by 4%.',
          'Increases your Parry chance by 5%.',
        ],
        row: 0,
        col: 1,
        points: 0,
        maxPoints: 5,
        icon: 'ability_parry.png',
      },

      {
        id: 'ability_gouge',
        name: 'Improved Rend',
        ranks: [
          'Increases the bleed damage done by your Rend ability by 25%.',
          'Increases the bleed damage done by your Rend ability by 50%.',
          'Increases the bleed damage done by your Rend ability by 75%.',
        ],
        row: 0,
        col: 2,
        points: 0,
        maxPoints: 3,
        icon: 'ability_gouge.png',
      },

      {
        id: 'ability_warrior_charge',
        name: 'Improved Charge',
        ranks: [
          'Increases the amount of rage generated by your Charge ability by 3.',
          'Increases the amount of rage generated by your Charge ability by 6.',
        ],
        row: 1,
        col: 0,
        points: 0,
        maxPoints: 2,
        icon: 'ability_warrior_charge.png',
      },

      {
        id: 'spell_magic_magearmor',
        name: 'Iron Will',
        ranks: [
          'Increases your chance to resist stun and charm effects by 3%.',
          'Increases your chance to resist stun and charm effects by 6%.',
          'Increases your chance to resist stun and charm effects by 9%.',
          'Increases your chance to resist stun and charm effects by 12%.',
          'Increases your chance to resist stun and charm effects by 15%.',
        ],
        row: 1,
        col: 1,
        points: 0,
        maxPoints: 5,
        icon: 'spell_magic_magearmor.png',
      },

      {
        id: 'ability_thunderclap',
        name: 'Improved Thunder Clap',
        ranks: [
          'Reduces the cost of your Thunder Clap ability by 1 rage point and increases its damage by 40% and the slowing effect by an additional 4%.',
          'Reduces the cost of your Thunder Clap ability by 2 rage points and increases its damage by 70% and the slowing effect by an additional 8%.',
          'Reduces the cost of your Thunder Clap ability by 4 rage points and increases its damage by 100% and the slowing effect by an additional 12%.',
        ],
        row: 1,
        col: 2,
        points: 0,
        maxPoints: 3,
        icon: 'ability_thunderclap.png',
      },

      {
        id: 'inv_sword_05',
        name: 'Improved Overpower',
        ranks: [
          'Increases the critical strike chance of your Overpower ability by 25%.',
          'Increases the critical strike chance of your Overpower ability by 50%.',
        ],
        row: 2,
        col: 0,
        points: 0,
        maxPoints: 2,
        icon: 'inv_sword_05.png',
      },

      {
        id: 'spell_holy_blessingofstamina',
        name: 'Anger Management',
        ranks: [
          'Generates 1 rage every 3 seconds while in combat.',
        ],
        row: 2,
        col: 1,
        points: 0,
        maxPoints: 1,
        icon: 'spell_holy_blessingofstamina.png',
      },

      {
        id: 'ability_backstab',
        name: 'Deep Wounds',
        ranks: [
          "Your critical strikes cause the opponent to bleed, dealing 20% of your melee weapon's average damage over 12 sec.",
          "Your critical strikes cause the opponent to bleed, dealing 40% of your melee weapon's average damage over 12 sec.",
          "Your critical strikes cause the opponent to bleed, dealing 60% of your melee weapon's average damage over 12 sec.",
        ],
        row: 2,
        col: 2,
        points: 0,
        maxPoints: 3,
        icon: 'ability_backstab.png',
      },

      {
        id: 'inv_axe_09',
        name: 'Two-Handed Weapon Specialization',
        ranks: [
          'Increases the damage you deal with two-handed melee weapons by 1%.',
          'Increases the damage you deal with two-handed melee weapons by 2%.',
          'Increases the damage you deal with two-handed melee weapons by 3%.',
          'Increases the damage you deal with two-handed melee weapons by 4%.',
          'Increases the damage you deal with two-handed melee weapons by 5%.',
        ],
        row: 3,
        col: 1,
        points: 0,
        maxPoints: 5,
        icon: 'inv_axe_09.png',
      },

      {
        id: 'ability_searingarrow',
        name: 'Impale',
        ranks: [
          'Increases the critical strike damage bonus of your abilities by 10%.',
          'Increases the critical strike damage bonus of your abilities by 20%.',
        ],
        row: 3,
        col: 2,
        points: 0,
        maxPoints: 2,
        icon: 'ability_searingarrow.png',
        requires: {
          id: 'ability_backstab',
          points: 3,
        },
      },

      {
        id: 'ability_warrior_decisivestrike',
        name: 'Improved Slam',
        ranks: [
          'Decreases the casting time of your Slam ability by 0.5 sec.',
          'Decreases the casting time of your Slam ability by 1 sec.',
        ],
        row: 3,
        col: 3,
        points: 0,
        maxPoints: 2,
        icon: 'ability_warrior_decisivestrike.png',
      },

      {
        id: 'inv_axe_06',
        name: 'Poleaxe Specialization',
        ranks: [
          'Increases your chance to get a critical strike with Axes and Polearms by 1%.',
          'Increases your chance to get a critical strike with Axes and Polearms by 2%.',
          'Increases your chance to get a critical strike with Axes and Polearms by 3%.',
          'Increases your chance to get a critical strike with Axes and Polearms by 4%.',
          'Increases your chance to get a critical strike with Axes and Polearms by 5%.',
        ],
        row: 4,
        col: 0,
        points: 0,
        maxPoints: 5,
        icon: 'inv_axe_06.png',
      },

      {
        id: 'ability_rogue_slicedice',
        name: 'Sweeping Strikes',
        ranks: [
          'Your next 10 melee attacks strike an additional nearby opponent.',
        ],
        row: 4,
        col: 1,
        points: 0,
        maxPoints: 1,
        icon: 'ability_rogue_slicedice.png',
      },

      {
        id: 'inv_mace_01',
        name: 'Mace Specialization',
        ranks: [
          'Gives your melee attacks a chance to stun your target for 3 seconds and generate 7 rage when using a Mace.',
          'Gives your melee attacks a chance to stun your target for 3 seconds and generate 7 rage when using a Mace. More effective than Mace Specialization (Rank 1).',
          'Gives your melee attacks a chance to stun your target for 3 seconds and generate 7 rage when using a Mace. More effective than Mace Specialization (Rank 2).',
          'Gives your melee attacks a chance to stun your target for 3 seconds and generate 7 rage when using a Mace. More effective than Mace Specialization (Rank 3).',
          'Gives your melee attacks a chance to stun your target for 3 seconds and generate 7 rage when using a Mace. More effective than Mace Specialization (Rank 4).',
        ],
        row: 4,
        col: 2,
        points: 0,
        maxPoints: 5,
        icon: 'inv_mace_01.png',
      },
      {
        id: 'inv_sword_27',
        name: 'Sword Specialization',
        ranks: [
          'Gives you a 1% chance to get an extra attack on the same target after hitting your target with your Sword.',
          'Gives you a 2% chance to get an extra attack on the same target after hitting your target with your Sword.',
          'Gives you a 3% chance to get an extra attack on the same target after hitting your target with your Sword.',
          'Gives you a 4% chance to get an extra attack on the same target after hitting your target with your Sword.',
          'Gives you a 5% chance to get an extra attack on the same target after hitting your target with your Sword.',
        ],
        row: 4,
        col: 3,
        points: 0,
        maxPoints: 5,
        icon: 'inv_sword_27.png',
      },

      {
        id: 'ability_rogue_sprint',
        name: 'Improved Intercept',
        ranks: [
          'Reduces the cooldown of your Intercept ability by 5 sec.',
          'Reduces the cooldown of your Intercept ability by 10 sec.',
        ],
        row: 5,
        col: 0,
        points: 0,
        maxPoints: 2,
        icon: 'ability_rogue_sprint.png',
      },

      {
        id: 'ability_shockwave',
        name: 'Improved Hamstring',
        ranks: [
          'Gives your Hamstring ability a 5% chance to immobilize the target for 5 seconds.',
          'Gives your Hamstring ability a 10% chance to immobilize the target for 5 seconds.',
          'Gives your Hamstring ability a 15% chance to immobilize the target for 5 seconds.',
        ],
        row: 5,
        col: 2,
        points: 0,
        maxPoints: 3,
        icon: 'ability_shockwave.png',
      },

      {
        id: 'ability_warrior_improveddisciplines',
        name: 'Improved Disciplines',
        ranks: [
          'Reduces the cooldown of your Retaliation, Recklessness and Shield Wall abilities by 4 min and increases their duration by 2 sec.',
          'Reduces the cooldown of your Retaliation, Recklessness and Shield Wall abilities by 7 min and increases their duration by 4 sec.',
          'Reduces the cooldown of your Retaliation, Recklessness and Shield Wall abilities by 10 min and increases their duration by 6 sec.',
        ],
        row: 5,
        col: 3,
        points: 0,
        maxPoints: 3,
        icon: 'ability_warrior_improveddisciplines.png',
      },

      {
        id: 'ability_warrior_bloodfrenzy',
        name: 'Blood Frenzy',
        ranks: [
          'Your Rend and Deep Wounds abilities also increase all physical damage caused to that target by 2%.',
          'Your Rend and Deep Wounds abilities also increase all physical damage caused to that target by 4%.',
        ],
        row: 6,
        col: 0,
        points: 0,
        maxPoints: 2,
        icon: 'ability_warrior_bloodfrenzy.png',
      },

      {
        id: 'ability_warrior_savageblow',
        name: 'Mortal Strike',
        ranks: [
          'A vicious strike that deals weapon damage plus 88 and wounds the target, reducing the effectiveness of any healing by 50% for 10 seconds.',
        ],
        row: 6,
        col: 1,
        points: 0,
        maxPoints: 1,
        icon: 'ability_warrior_savageblow.png',
        requires: {
          id: 'ability_rogue_slicedice',
          points: 1,
        },
      },
      {
        id: 'ability_hunter_harass',
        name: 'Second Wind',
        ranks: [
          'Whenever you are struck by a Stun or Immobilize effect you will generate 10 rage and 5% of your total health over 10 sec.',
          'Whenever you are struck by a Stun or Immobilize effect you will generate 20 rage and 10% of your total health over 10 sec.',
        ],
        row: 6,
        col: 2,
        points: 0,
        maxPoints: 2,
        icon: 'ability_hunter_harass.png',
      },

      {
        id: 'ability_warrior_endlessrage',
        name: 'Endless Rage',
        ranks: [
          'You generate 8% more rage from damage dealt.',
          'You generate 16% more rage from damage dealt.',
          'You generate 25% more rage from damage dealt.',
        ],
        row: 7,
        col: 1,
        points: 0,
        maxPoints: 3,
        icon: 'ability_warrior_endlessrage.png',
      },

      {
        id: 'ability_warrior_bloodbath',
        name: 'Empowered Rend',
        ranks: [
          'The damage dealt by Rend is 0.5 second faster.',
          'The damage dealt by Rend is 1 second faster.',
        ],
        row: 7,
        col: 2,
        points: 0,
        maxPoints: 2,
        icon: 'ability_warrior_bloodbath.png',
      },
      {
        id: 'ability_warrior_bladestorm',
        name: 'Bladestorm',
        ranks: [
          'Instantly Whirlwind up to 4 nearby targets and for the next 6 seconds you will perform a whirlwind attack every 1 seconds sec. While under the effects of Bladestorm, you can move but cannot perform any other abilities but you do not feel pity or remorse or fear, you cannot be stopped unless killed, and your movement speed cannot be reduced below 60%.',
        ],
        row: 8,
        col: 1,
        points: 0,
        maxPoints: 1,
        icon: 'ability_warrior_bladestorm.png',
        abilityData: {
          leftSide: [
            "25 Rage",
            "Instant cast",
          ],
          rightSide: [
            "",
            "1.5 min cooldown"
          ],
          bottom: [
            "Requires Melee Weapon"
          ]
        }
      },
    ],
  },
]
