import type { Tree } from './types'

export const initialTalentTrees: Tree[] = [
  {
    name: "Arms",
    backgroundImage: "src/assets/images/warrior/background-warrior-arms.jpg",
    talents: [
      {
        id: "improved_heroic_strike",
        name: "Improved Heroic Strike",
        ranks: [
          "Reduces the cost of your Heroic Strike ability by 1 rage point.",
          "Reduces the cost of your Heroic Strike ability by 2 rage points.",
          "Reduces the cost of your Heroic Strike ability by 3 rage points."
        ],
        row: 0,
        col: 0,
        maxPoints: 3,
        icon: "ability_rogue_ambush.jpg",
        points: 0
      },
      {
        id: "deflection",
        name: "Deflection",
        ranks: [
          "Increases your Parry chance by 1%.",
          "Increases your Parry chance by 2%.",
          "Increases your Parry chance by 3%.",
          "Increases your Parry chance by 4%.",
          "Increases your Parry chance by 5%."
        ],
        row: 0,
        col: 1,
        maxPoints: 5,
        icon: "ability_parry.jpg",
        points: 0
      },
      {
        id: "improved_rend",
        name: "Improved Rend",
        ranks: [
          "Increases the bleed damage done by your Rend ability by 25%.",
          "Increases the bleed damage done by your Rend ability by 50%.",
          "Increases the bleed damage done by your Rend ability by 75%."
        ],
        row: 0,
        col: 2,
        maxPoints: 3,
        icon: "ability_gouge.jpg",
        points: 0
      },
      {
        id: "improved_charge",
        name: "Improved Charge",
        ranks: [
          "Increases the amount of rage generated by your Charge ability by 3.",
          "Increases the amount of rage generated by your Charge ability by 6."
        ],
        row: 1,
        col: 0,
        maxPoints: 2,
        icon: "ability_warrior_charge.jpg",
        points: 0
      },
      {
        id: "iron_will",
        name: "Iron Will",
        ranks: [
          "Increases your chance to resist stun and charm effects by 3%.",
          "Increases your chance to resist stun and charm effects by 6%.",
          "Increases your chance to resist stun and charm effects by 9%.",
          "Increases your chance to resist stun and charm effects by 12%.",
          "Increases your chance to resist stun and charm effects by 15%."
        ],
        row: 1,
        col: 1,
        maxPoints: 5,
        icon: "spell_magic_magearmor.jpg",
        points: 0
      },
      {
        id: "improved_thunder_clap",
        name: "Improved Thunder Clap",
        ranks: [
          "Reduces the cost of your Thunder Clap ability by 1 rage point and increases its damage by 40%.",
          "Reduces the cost of your Thunder Clap ability by 2 rage points and increases its damage by 70%.",
          "Reduces the cost of your Thunder Clap ability by 4 rage points and increases its damage by 100%."
        ],
        row: 1,
        col: 2,
        maxPoints: 3,
        icon: "ability_thunderclap.jpg",
        points: 0
      },
      {
        id: "improved_overpower",
        name: "Improved Overpower",
        ranks: [
          "Increases the critical strike chance of your Overpower ability by 25%.",
          "Increases the critical strike chance of your Overpower ability by 50%."
        ],
        row: 2,
        col: 0,
        maxPoints: 2,
        icon: "inv_sword_05.jpg",
        points: 0
      },
      {
        id: "anger_management",
        name: "Anger Management",
        ranks: [
          "Generates 1 rage every 3 seconds while in combat."
        ],
        row: 2,
        col: 1,
        maxPoints: 1,
        icon: "spell_holy_blessingofstamina.jpg",
        points: 0
      },
      {
        id: "deep_wounds",
        name: "Deep Wounds",
        ranks: [
          "Your critical strikes cause the opponent to bleed, dealing 20% of your melee weapon's average damage over 12 sec.",
          "Your critical strikes cause the opponent to bleed, dealing 40% of your melee weapon's average damage over 12 sec.",
          "Your critical strikes cause the opponent to bleed, dealing 60% of your melee weapon's average damage over 12 sec."
        ],
        row: 2,
        col: 2,
        maxPoints: 3,
        icon: "ability_backstab.jpg",
        points: 0
      },
      {
        id: "two_handed_weapon_specialization",
        name: "Two-Handed Weapon Specialization",
        ranks: [
          "Increases the damage you deal with two-handed melee weapons by 1%.",
          "Increases the damage you deal with two-handed melee weapons by 2%.",
          "Increases the damage you deal with two-handed melee weapons by 3%.",
          "Increases the damage you deal with two-handed melee weapons by 4%.",
          "Increases the damage you deal with two-handed melee weapons by 5%."
        ],
        row: 3,
        col: 1,
        maxPoints: 5,
        icon: "inv_axe_09.jpg",
        points: 0
      },
      {
        id: "impale",
        name: "Impale",
        ranks: [
          "Increases the critical strike damage bonus of your abilities by 10%.",
          "Increases the critical strike damage bonus of your abilities by 20%."
        ],
        row: 3,
        col: 2,
        maxPoints: 2,
        icon: "ability_searingarrow.jpg",
        requires: { id: "deep_wounds", points: 3 },
        points: 0
      },
      {
        id: "axe_specialization",
        name: "Axe Specialization",
        ranks: [
          "Increases your chance to get a critical strike with Axes and Polearms by 1%.",
          "Increases your chance to get a critical strike with Axes and Polearms by 2%.",
          "Increases your chance to get a critical strike with Axes and Polearms by 3%.",
          "Increases your chance to get a critical strike with Axes and Polearms by 4%.",
          "Increases your chance to get a critical strike with Axes and Polearms by 5%."
        ],
        row: 4,
        col: 1,
        maxPoints: 5,
        icon: "inv_sword_27.jpg",
        points: 0
      },
      {
        id: "death_wish",
        name: "Death Wish",
        ranks: [
          "When activated, increases your physical damage by 20% but increases all damage taken by 5%. Lasts 30 sec."
        ],
        row: 4,
        col: 0,
        maxPoints: 1,
        icon: "inv_axe_06.jpg",
        points: 0
      },
      {
        id: "improved_intercept",
        name: "Improved Intercept",
        ranks: [
          "Reduces the cooldown of your Intercept ability by 5 sec.",
          "Reduces the cooldown of your Intercept ability by 10 sec."
        ],
        row: 4,
        col: 2,
        maxPoints: 2,
        icon: "ability_rogue_slicedice.jpg",
        points: 0
      },
      {
        id: "mortal_strike",
        name: "Mortal Strike",
        ranks: [
          "A vicious strike that deals weapon damage and wounds the target, reducing the effectiveness of any healing by 50% for 10 sec."
        ],
        row: 5,
        col: 2,
        maxPoints: 1,
        icon: "ability_shockwave.jpg",
        requires: { id: "impale", points: 2 },
        points: 0
      },
      {
        id: "second_wind",
        name: "Second Wind",
        ranks: [
          "Whenever you are struck by a Stun or Immobilize effect you will generate 10 rage and 10% of your total health over 10 sec.",
          "Whenever you are struck by a Stun or Immobilize effect you will generate 20 rage and 20% of your total health over 10 sec."
        ],
        row: 6,
        col: 1,
        maxPoints: 2,
        icon: "ability_hunter_harass.jpg",
        points: 0
      },
      {
        id: "improved_mortal_strike",
        name: "Improved Mortal Strike",
        ranks: [
          "Reduces the cooldown of your Mortal Strike ability by 0.2 sec.",
          "Reduces the cooldown of your Mortal Strike ability by 0.4 sec.",
          "Reduces the cooldown of your Mortal Strike ability by 0.6 sec.",
          "Reduces the cooldown of your Mortal Strike ability by 0.8 sec.",
          "Reduces the cooldown of your Mortal Strike ability by 1 sec."
        ],
        row: 6,
        col: 2,
        maxPoints: 5,
        icon: "ability_warrior_savageblow.jpg",
        requires: { id: "mortal_strike", points: 1 },
        points: 0
      },
      {
        id: "blood_frenzy",
        name: "Blood Frenzy",
        ranks: [
          "Your Rend and Deep Wounds abilities also increase all physical damage caused to that target by 2%.",
          "Your Rend and Deep Wounds abilities also increase all physical damage caused to that target by 4%."
        ],
        row: 6,
        col: 0,
        maxPoints: 2,
        icon: "ability_warrior_bloodfrenzy.jpg",
        points: 0
      },
      {
        id: "endless_rage",
        name: "Endless Rage",
        ranks: [
          "You generate 25% more rage from damage dealt."
        ],
        row: 7,
        col: 1,
        maxPoints: 1,
        icon: "ability_warrior_endlessrage.jpg",
        points: 0
      }
    ]
  },
]
