import type { Tree } from '../../types'

export const protection: Tree = {
  name: 'Protection',
  backgroundImage:
    'src/assets/images/warrior/background-warrior-protection.webp',
  specIcon: 'ability_warrior_defensivestance.png',
  talents: [
    // Row 0
    {
      row: 0,
      col: 0,
      icon: 'ability_racial_bloodrage.png',
      id: 'ability_racial_bloodrage',
      name: 'Improved Bloodrage',
      points: 0,
      maxPoints: 2,
      ranks: [
        'Increases the instant rage generated by your Bloodrage ability by 3.',
        'Increases the instant rage generated by your Bloodrage ability by 6.',
      ],
    },
    {
      row: 0,
      col: 1,
      icon: 'spell_nature_enchantarmor.png',
      id: 'spell_nature_enchantarmor',
      name: 'Tactical Mastery',
      points: 0,
      maxPoints: 3,
      ranks: [
        'You retain up to 5 of your rage points when you change stances. Also greatly increases the threat generated by your Bloodthirst and Mortal Strike abilities when you are in Defensive Stance.',
        'You retain up to 10 of your rage points when you change stances. Also greatly increases the threat generated by your Bloodthirst and Mortal Strike abilities when you are in Defensive Stance (More effective than Rank 1).',
        'You retain up to 15 of your rage points when you change stances. Also greatly increases the threat generated by your Bloodthirst and Mortal Strike abilities when you are in Defensive Stance (More effective than Rank 2).',
      ],
    },
    {
      row: 0,
      col: 2,
      icon: 'spell_nature_mirrorimage.png',
      id: 'spell_nature_mirrorimage',
      name: 'Anticipation',
      points: 0,
      maxPoints: 5,
      ranks: [
        'Increases your Defense skill by 4.',
        'Increases your Defense skill by 8.',
        'Increases your Defense skill by 12.',
        'Increases your Defense skill by 16.',
        'Increases your Defense skill by 20.',
      ],
    },

    // Row 1
    {
      row: 1,
      col: 1,
      icon: 'inv_shield_06.png',
      id: 'inv_shield_06',
      name: 'Shield Specialization',
      points: 0,
      maxPoints: 5,
      ranks: [
        'Increases your chance to block attacks with a shield by 2% and gives you a 40% chance to generate 1 rage point when a block occurs.',
        'Increases your chance to block attacks with a shield by 1% and gives you a 20% chance to generate 1 rage point when a block occurs.',
        'Increases your chance to block attacks with a shield by 3% and gives you a 60% chance to generate 1 rage point when a block occurs.',
        'Increases your chance to block attacks with a shield by 4% and gives you a 80% chance to generate 1 rage point when a block occurs.',
        'Increases your chance to block attacks with a shield by 5% and gives you a 100% chance to generate 1 rage point when a block occurs.',
      ],
    },
    {
      row: 1,
      col: 2,
      icon: 'spell_holy_devotion.png',
      id: 'spell_holy_devotion',
      name: 'Toughness',
      points: 0,
      maxPoints: 5,
      ranks: [
        'Increases your armor value from items by 2%.',
        'Increases your armor value from items by 4%.',
        'Increases your armor value from items by 6%.',
        'Increases your armor value from items by 8%.',
        'Increases your armor value from items by 10%.',
      ],
    },

    // Row 2
    {
      row: 2,
      col: 0,
      icon: 'spell_holy_ashestoashes.png',
      id: 'spell_holy_ashestoashes',
      name: 'Last Stand',
      points: 0,
      maxPoints: 1,
      ranks: [
        'When activated, this ability temporarily grants you 30% of your maximum health for 20 seconds. After the effect expires, the health is lost.',
      ],
      abilityData: {
        leftSide: ['Instant'],
        rightSide: ['8 min cooldown'],
      },
    },
    {
      row: 2,
      col: 1,
      icon: 'ability_defend.png',
      id: 'ability_defend',
      name: 'Improved Shield Block',
      points: 0,
      maxPoints: 1,
      ranks: [
        'Allows you to block an additional attack and increases the duration of your Shield Block ability by 1 second.',
      ],
      requires: {
        id: 'inv_shield_06',
        points: 5,
      },
    },
    {
      row: 2,
      col: 2,
      icon: 'ability_warrior_revenge.png',
      id: 'ability_warrior_revenge',
      name: 'Improved Revenge',
      points: 0,
      maxPoints: 3,
      ranks: [
        'Gives your Revenge ability a 15% chance to stun the target for 3 seconds.',
        'Gives your Revenge ability a 30% chance to stun the target for 3 seconds.',
        'Gives your Revenge ability a 45% chance to stun the target for 3 seconds.',
      ],
    },
    {
      row: 2,
      col: 3,
      icon: 'ability_warrior_innerrage.png',
      id: 'ability_warrior_innerrage',
      name: 'Defiance',
      points: 0,
      maxPoints: 3,
      ranks: [
        'Increases the threat generated by your attacks by 5% while in Defensive Stance and reduces your chance to be dodged or parried by 0.5%.',
        'Increases the threat generated by your attacks by 10% while in Defensive Stance and reduces your chance to be dodged or parried by 1%.',
        'Increases the threat generated by your attacks by 15% while in Defensive Stance and reduces your chance to be dodged or parried by 1.5%.',
      ],
    },

    // Row 3
    {
      row: 3,
      col: 0,
      icon: 'ability_warrior_sunder.png',
      id: 'ability_warrior_sunder',
      name: 'Improved Sunder Armor',
      points: 0,
      maxPoints: 3,
      ranks: [
        'Reduces the cost of your Sunder Armor ability by 1 rage point.',
        'Reduces the cost of your Sunder Armor ability by 2 rage points.',
        'Reduces the cost of your Sunder Armor ability by 3 rage points.',
      ],
    },
    {
      row: 3,
      col: 1,
      icon: 'ability_warrior_disarm.png',
      id: 'ability_warrior_disarm',
      name: 'Improved Disarm',
      points: 0,
      maxPoints: 3,
      ranks: [
        'Increases the duration of your Disarm ability by 1 second.',
        'Increases the duration of your Disarm ability by 2 seconds.',
        'Increases the duration of your Disarm ability by 3 seconds.',
      ],
    },
    {
      row: 3,
      col: 2,
      icon: 'spell_nature_reincarnation.png',
      id: 'spell_nature_reincarnation',
      name: 'Improved Taunt',
      points: 0,
      maxPoints: 2,
      ranks: [
        'Reduces the cooldown of your Taunt ability by 1 second and increases its range by 7 yards.',
        'Reduces the cooldown of your Taunt ability by 2 seconds and increases its range by 15 yards.',
      ],
    },

    // Row 4
    {
      row: 4,
      col: 0,
      icon: 'ability_warrior_shieldwall.png',
      id: 'ability_warrior_shieldwall',
      name: 'Improved Shield Wall',
      points: 0,
      maxPoints: 2,
      ranks: [
        'Increases the duration of your Shield Wall ability by 3 sec.',
        'Increases the duration of your Shield Wall ability by 5 sec.',
      ],
    },
    {
      row: 4,
      col: 1,
      icon: 'ability_thunderbolt.png',
      id: 'ability_thunderbolt',
      name: 'Concussion Blow',
      points: 0,
      maxPoints: 1,
      ranks: [
        'Stuns the opponent for 5 seconds.',
      ],
      abilityData: {
        leftSide: ['15 Rage', 'Instant'],
        rightSide: [
          'Melee Range',
          '45 sec cooldown',
        ],
        bottom: ['Requires Melee Weapon'],
      },
    },
    {
      row: 4,
      col: 2,
      icon: 'ability_warrior_shieldbash.png',
      id: 'ability_warrior_shieldbash',
      name: 'Improved Shield Bash',
      points: 0,
      maxPoints: 2,
      ranks: [
        'Gives your Shield Bash ability a 50% chance to silence the target for 3 seconds.',
        'Gives your Shield Bash ability a 100% chance to silence the target for 3 seconds.',
      ],
    },

    // Row 5
    {
      row: 5,
      col: 0,
      icon: 'ability_warrior_shieldmastery.png',
      id: 'ability_warrior_shieldmastery',
      name: 'Shield Mastery',
      points: 0,
      maxPoints: 3,
      ranks: [
        'Increases the damage absorbed by your shield by 10%.',
        'Increases the damage absorbed by your shield by 20%.',
        'Increases the damage absorbed by your shield by 30%.',
      ],
    },
    {
      row: 5,
      col: 2,
      icon: 'inv_sword_20.png',
      id: 'inv_sword_20',
      name: 'One-Handed Weapon Specialization',
      points: 0,
      maxPoints: 5,
      ranks: [
        'Increases physical damage you deal when a one-handed melee weapon is equipped by 2%.',
        'Increases physical damage you deal when a one-handed melee weapon is equipped by 4%.',
        'Increases physical damage you deal when a one-handed melee weapon is equipped by 6%.',
        'Increases physical damage you deal when a one-handed melee weapon is equipped by 8%.',
        'Increases physical damage you deal when a one-handed melee weapon is equipped by 10%.',
      ],
    },

    // Row 6
    {
      row: 6,
      col: 0,
      icon: 'ability_warrior_defensivestance.png',
      id: 'ability_warrior_defensivestance',
      name: 'Improved Defensive Stance',
      points: 0,
      maxPoints: 3,
      ranks: [
        'Reduces all spell damage taken while in Defensive Stance by 2%.',
        'Reduces all spell damage taken while in Defensive Stance by 4%.',
        'Reduces all spell damage taken while in Defensive Stance by 6%.',
      ],
    },
    {
      row: 6,
      col: 1,
      icon: 'inv_shield_05.png',
      id: 'inv_shield_05',
      name: 'Shield Slam',
      points: 0,
      maxPoints: 1,
      ranks: [
        'Slams the target with your shield, causing 225 damage, modified by your shield block value, and dispels 1 magic effect on the target. Also causes a high amount of threat.',
      ],
      requires: {
        id: 'ability_warrior_shieldwall',
        points: 1,
      },
      abilityData: {
        leftSide: [
            '20 Rage',
            'Instant'
        ],
        rightSide: [
            'Melee Range',
            '6 sec cooldown'
        ]
      },
    },
    {
      row: 6,
      col: 2,
      icon: 'ability_warrior_focusedrage.png',
      id: 'ability_warrior_focusedrage',
      name: 'Focused Rage',
      points: 0,
      maxPoints: 3,
      ranks: [
        'Reduces the rage cost of your offensive abilities by 1.',
        'Reduces the rage cost of your offensive abilities by 2.',
        'Reduces the rage cost of your offensive abilities by 3.',
      ],
    },

    // Row 7
    {
      row: 7,
      col: 1,
      icon: 'inv_helmet_21.png',
      id: 'inv_helmet_21',
      name: 'Vitality',
      points: 0,
      maxPoints: 5,
      ranks: [
        'Increases your total Stamina by 1% and your total Strength by 2%.',
        'Increases your total Stamina by 2% and your total Strength by 4%.',
        'Increases your total Stamina by 3% and your total Strength by 6%.',
        'Increases your total Stamina by 4% and your total Strength by 8%.',
        'Increases your total Stamina by 5% and your total Strength by 10%.',
      ],
    },

    // Row 8
    {
      row: 8,
      col: 1,
      icon: 'inv_sword_11.png',
      id: 'inv_sword_11',
      name: 'Devastate',
      points: 0,
      maxPoints: 1,
      ranks: [
        `Sunder the target's armor causing the Sunder Armor effect. 
        In addition, causes 50% of weapon damage plus 15 for each application of Sunder Armor on the target. 
        The Sunder Armor effect can stack up to 5 times.`,
      ],
      abilityData: {
        leftSide: [
            '15 Rage',
            'Instant'
        ],
        rightSide: [
            'Melee Range'
        ],
        bottom: [
            'Requires One-Handed Melee Weapon'
        ]
      }
    },
  ],
}
